# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [22]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0,0,1,1]]).T

In [23]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,3)) - 1
# define syn1
syn1 = 2*np.random.random((3,1)) - 1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）

syn0_history = [syn0]
syn1_history = [syn1]

神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [24]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    # how much did we miss?
    l2_error = y - l2
    
    if (iter% 1000) == 0: # every 1000 trains it will print
        print ('l2@iter: ', iter, )
        print(str(l2))
        print ("Error: " + str(np.mean(np.abs(l2_error))))
 
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error * nonlin(l2,True)
    
    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,True)
    
    # update weights
    syn1 += l1.T.dot(l2_delta) 
    #backpropagation
    syn0 += np.dot(l0.T,l1_delta)
    
print("Output After Training:")
print(l1)
print("\n\n")
print(l2)

l2@iter:  0
[[0.53115087]
 [0.51889166]
 [0.50584798]
 [0.50081188]]
Error: 0.5108456683181674
l2@iter:  1000
[[0.0202188 ]
 [0.01653029]
 [0.98105032]
 [0.97900926]]
Error: 0.01917237865103627
l2@iter:  2000
[[0.01346461]
 [0.01111736]
 [0.9872274 ]
 [0.98591841]]
Error: 0.012859039692932771
l2@iter:  3000
[[0.01070434]
 [0.00888895]
 [0.98977949]
 [0.98876045]]
Error: 0.010263336267434206
l2@iter:  4000
[[0.00912053]
 [0.00760388]
 [0.99125323]
 [0.9903973 ]]
Error: 0.008768471246155351
l2@iter:  5000
[[0.00806517]
 [0.00674434]
 [0.99223969]
 [0.99149089]]
Error: 0.007769735106145149
l2@iter:  6000
[[0.00729917]
 [0.00611858]
 [0.99295816]
 [0.99228624]]
Error: 0.007043338393890519
l2@iter:  7000
[[0.00671143]
 [0.00563722]
 [0.99351099]
 [0.99289751]]
Error: 0.006485037009613113
l2@iter:  8000
[[0.00624247]
 [0.00525233]
 [0.99395312]
 [0.9933859 ]]
Error: 0.00603894387910843
l2@iter:  9000
[[0.00585728]
 [0.00493559]
 [0.994317  ]
 [0.99378753]]
Error: 0.005672084899869198
Output 